function B = B_CloopZ(r,z0,R,I);
%
% 2nd order approximation for the B field generated by a SINGLE coil loop
% displaced by z0 from the origin on the Z axis, eq.(3), pg.2. notes:
% Todd Meyrath, "ELECTROMAGNET DESIGN BASICS FOR COLD ATOM EXPERIMENTS" 
% (Jan/2004)
%
% NOTE: by comparing the full expression, eqs.(1)&(2) results w/ those 
% given by the eq.(6) (see below), it seems that one can go not further 
% than 1mm apart from the origin. Otherwise, the results diverge much from
% each other.
%
x = r(1); y = r(2); z = r(3);
rho = sqrt( x.^2 + y.^2 );
%
Bz = (1/2)*R^2/( (z-z0)^2 + R^2 )^(3/2) + (3/2)*z*(z-z0)*R^2/( (z-z0)^2 + R^2 )^(5/2) + (3/4)*R^2*(4*(z-z0)^2 - R^2)*(z^2 - rho^2/2)/( (z-z0)^2 + R^2 )^(7/2);
%Br = -(3/4)*rho*(z-z0)*R^2/( (z-z0)^2 + R^2 )^(5/2) - (3/4)*R^2*(4*(z-z0)^2 - R^2)*z*rho/( (z-z0)^2 + R^2 )^(7/2);
%co= x/rho; si= y/rho;
mu = 0.4*pi; % mu0 in CGS units (G*cm/A)
%
B = I*mu*[0 0 Bz];